# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xV9_Z3IZD3B0OMkR7tlJTWtgltyyYqie
"""

import openpyxl
from scipy.integrate import quad
# Lendo a planilha
workbook = openpyxl.load_workbook('/content/Dimensionamento de Longarina (Asa).xlsx')

#Acessando a celula
sheet = workbook.active
celula = sheet['C4']
valor = celula.value
print(celula.value)

#Tornando a equação legivel
import re
e = celula.value
e = re.sub(r'x(\d)', r'x**\1', e)
e = e.replace(',', '.')
e = e.replace('x','*x')
e, r2 = e.split('R²')
e = e.replace('y =', '')
print(e)

#Definindo valor para o grafico
import numpy as np
import matplotlib.pyplot as plt

def f(x):
    return eval(e)
x = np.linspace(-10, 10, 400)
y = f(x)

plt.plot(x, y)
plt.show()

import re
#Calculando esforco cortante
partes = re.findall(r'[+-]?\s*\d+\.\d+\*x\*\*\d+|[+-]?\s*\d+\.\d+', e)
partes = partes[::-1]
resultados = []
for i, parte in enumerate(partes):
    if i < 7:
        valor = eval(parte)
        resultado = valor / (i+1)
        resultados.append(resultado)

ESFORÇO_CORTANTE = " + ".join(str(resultado) for resultado in resultados)
print(ESFORÇO_CORTANTE)

import matplotlib.pyplot as plt
import numpy as np

# Invertendo a equação
ESFORÇO_CORTANTE = ESFORÇO_CORTANTE.split(" + ")[::-1]
ESFORÇO_CORTANTE = " + ".join(ESFORÇO_CORTANTE)

#grafico esforco cortante
x = np.linspace(-10, 10, 400)
y = [eval(term) for term in ESFORÇO_CORTANTE.split(" + ")]

plt.figure(figsize=(10, 5))
plt.plot(x, y)
plt.title("Gráfico da Equação de Esforço Cortante")
plt.xlabel("x")
plt.ylabel("y")
plt.show()